"""
notepad.py: Generated by Codex as part of the PyCodex project
"""

import tkinter as tk
from tkinter import filedialog

class Notepad:
    def __init__(self):
        self.text = ''
        self.font = ('Arial', 12)
        self.size = (600, 400)

        self.root = tk.Tk()
        self.root.title('Untitled - Notepad')
        self.root.geometry('600x400')

        self.text_area = tk.Text(self.root, font=self.font)
        self.scroll_bar = tk.Scrollbar(self.root)
        self.scroll_bar.pack(side=tk.RIGHT, fill=tk.Y)
        self.text_area.pack(fill=tk.BOTH, expand=True)
        self.scroll_bar.config(command=self.text_area.yview)
        self.text_area.config(yscrollcommand=self.scroll_bar.set)

        self.menu_bar = tk.Menu(self.root)
        self.file_menu = tk.Menu(self.menu_bar, tearoff=0)
        self.file_menu.add_command(label='New', command=self.new_file)
        self.file_menu.add_command(label='Open', command=self.open_file)
        self.file_menu.add_command(label='Save', command=self.save_file)
        self.file_menu.add_separator()
        self.file_menu.add_command(label='Exit', command=self.root.quit)
        self.menu_bar.add_cascade(label='File', menu=self.file_menu)

        self.root.config(menu=self.menu_bar)

    def new_file(self):
        self.root.title('Untitled - Notepad')
        self.text_area.delete(1.0, tk.END)

    def open_file(self):
        file = filedialog.askopenfile(parent=self.root, mode='rb', title='Select a text file',
                                      filetypes=(('Text files', '*.txt'), ('All files', '*.*')))
        if file is not None:
            contents = file.read()
            self.text_area.insert('1.0', contents)
            file.close()

    def save_file(self):
        file = filedialog.asksaveasfile(mode='w', filetypes=(('Text files', '*.txt'), ('All files', '*.*')))
        if file is not None:
            data = self.text_area.get('1.0', tk.END + '-1c')
            file.write(data)
            file.close()


if __name__ == '__main__':
    notepad = Notepad()
    notepad.root.mainloop()
