"""
pwdgen.py: Generated by Codex as part of the PyCodex project
"""

from tkinter import *
import random
import string

root = Tk()
root.title("Password Generator")
root.geometry("400x400")

# Functions
def generate():
    password = []

    for i in range(5):
        upper = [random.choice(string.ascii_uppercase)]
        lower = [random.choice(string.ascii_lowercase)]
        numbers = random.choice(string.digits)
        symbols = random.choice(string.punctuation)

        password.extend(upper)
        password.extend(lower)
        password.append(numbers)
        password.append(symbols)

    y = "".join(str(x) for x in password)
    password_entry.delete(0, END)
    password_entry.insert(0, y)

# Label
Label(root, text="Password Generator Application", font="calibri 20 bold").pack()
Label(root, text="Enter your name").pack(pady=3)

# Entry
name_entry = Entry(root)
name_entry.pack(pady=3)

# Button
Button(root, text="Generate Password", command=generate).pack(pady=7)

# Entry
password_entry = Entry(root)
password_entry.pack(pady=3)

root.mainloop()
